export const armorList = [
  {
    name: "Ice Scales",
    image: "item-00219.png",
    slug: "icescales",
    id: "00219",
    category: "armor",
  },
  {
    name: "Drake Scales",
    image: "item-00220.png",
    slug: "drakescales",
    id: "00220",
    category: "armor",
  },
  {
    name: "Star Robe",
    image: "item-00238.png",
    slug: "starrobe",
    id: "00238",
    category: "armor",
  },
  {
    name: "Crocodile Boots",
    image: "item-00122.png",
    slug: "crocodileboots",
    id: "00122",
    category: "armor",
  },
  {
    name: "Feather Fall Boots",
    image: "item-00131.png",
    slug: "featherfallboots",
    id: "00131",
    category: "armor",
  },
  {
    name: "Steel Gauntlets",
    image: "item-00069.png",
    slug: "steelgauntlets",
    id: "00069",
    category: "armor",
  },
  {
    name: "Griffin Skull",
    image: "item-00035.png",
    slug: "griffinskull",
    id: "00035",
    category: "armor",
  },
];
