export const potionList = [
  {
    name: "Strength Potion",
    image: "item-00225.png",
    slug: "strengthpotion",
    id: "00225",
    category: "potions",
  },
  {
    name: "Dexterity Potion",
    image: "item-00222.png",
    slug: "dexteritypotion",
    id: "00222",
    category: "potions",
  },
  {
    name: "Intelligence Potion",
    image: "item-00216.png",
    slug: "intelligencepotion",
    id: "00216",
    category: "potions",
  },
  {
    name: "Wisdom Potion",
    image: "item-00274.png",
    slug: "wisdompotion",
    id: "00274",
    category: "potions",
  },
  {
    name: "Willpower Potion",
    image: "item-00289.png",
    slug: "willpowerpotion",
    id: "00289",
    category: "potions",
  },
  {
    name: "Constitution Potion",
    image: "item-00303.png",
    slug: "constitutionpotion",
    id: "00303",
    category: "potions",
  },
  {
    name: "Youth Potion",
    image: "item-00227.png",
    slug: "youthpotion",
    id: "00227",
    category: "potions",
  },
  {
    name: "Mana Replenishment Potion",
    image: "item-00006.png",
    slug: "manareplenishmentpotion",
    id: "00006",
    category: "potions",
  },
  {
    name: "Permanent Mana Potion",
    image: "item-00316.png",
    slug: "permanentmanapotion",
    id: "00227",
    category: "potions",
  },
];
